@startuml
Builder <-- Director
Builder <|-- ConcreteBuilder
Product <-- ConcreteBuilder

class Builder {
    - BuildPart()
}

class Director {
    - Construct()
}

class ConcreteBuilder {

}

class Product{
    - BuildPart()
    - GetResult()
}
@enduml
