@startuml
Prototype <-- Client
Prototype <|-- ConcretePrototype1
Prototype <|-- ConcretePrototype2

class Client {
    - Prototype p = prototype->clone();
}

class Prototype {
    - virtual clone() = 0;
}

class ConcretePrototype1 {
    - return clone() { new ConcretePrototype1 }
}

class ConcretePrototype2 {
    - return clone() { new ConcretePrototype2 }
}

@enduml