@startuml
Factory <|-- ConcreteFactory
Product <|-- ConcreteProduct
ConcreteFactory <-- ConcreteProduct


class Factory{
    - Product factoryMethod()
}

class ConcreteFactory {
    - Product factoryMethod()
}

class Product{

}

class ConcreteProduct {

}
@enduml
